bootdo:
  uploadPath: D:/var/uploaded_files/
logging:
  level:
    root: debug
    com.bootdo: debug
    com.bootdo.security: debug
    com.alibaba.druid.pool: debug
  file: /var/log/seven-mo/flowable-service/flowable-service.log
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.112.4.150:3306/fw65?useUnicode=true&characterEncoding=utf8
    username: root
    password: Bansenxu123abc!!!!!
    #url: ENC(N55qN9yxOuboFtK0H+ivxApdKZrzAcVxwkFYMN7p+4rTHwRAsWd6fOETmh4SW55MWgQJh91RBhUG5TSy557lQo+/wjcb/LK3Hu0x6E2ZIUTC6GJAVuaaGDJdEV2iC1TC)
    # username: ENC(BZLHGb4UjsoE+sr6mgwCl/PhQQnOBHzL)
    # password: ENC(ZWfu/1qlvAuRo0wo1CKBTBfrd8lp38k1epajUh+qEYWwOlqv5+PKexqT9i36XCL6CzcCbQBlS3+LvMjRqY5DiQ==)
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    host: localhost
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        
        max-wait: -1
server:
  port: 8202
  max-http-header-size: 1024000
  
flowable:
  mail:
    server:
      host: smtp.qq.com
      port: 587
      defaultFrom: 358402521@qq.com
      username: 358402521@qq.com
      password: alafhuytgmaabhbd
      useSsl: true
keycloak:
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArNqy1DIU20Ag7OWxzwqcnKyMRE636pVNuymRkT/9ZH3UT1pm9n5OoQ6kOlTG9s9T/I4f+FOPVsK21StCUgqKxOfTXf7DCO6hsc0Uta3lzX1fQ1oudRsfwHT/9KO0jBbZ6VZsZDqoekKl7qH3dpRmwpMzyW9Hvb3JUt1OBWPnBFRXVjG4ItrkMadTJ1gtlZ1JZEoymGEWYQJ8+2+eo+N+4Ws37WTkabd+vbEYN0kHdR5LhCqG14QRNf/Ko+sN823IjvJqKgOriNWUOZFv6HozBOjic9x3uYVlwk+WwhYvwKkPyS+tPB7cBF0Nor8/F4UOfMbowhfc9eZCtJmzm8uLewIDAQAB
  