bootdo:
  uploadPath: D:/var/uploaded_files/
  keycloak_username: admin
  keycloak_password: admin
  keycloak_realmname: master
  keycloak_url: http://10.10.10.5:8080/auth
  keycloak_client_id: admin-cli

  flowable_url: jdbc:mysql://localhost:3306/workflow?useUnicode=true&characterEncoding=utf8
  flowable_username: root
  flowable_password: 123
  flowable_driver_name: com.mysql.jdbc.Driver
  
logging:
  level:
    root: info
    #    com.bootdo: debug
    com.bootdo.security: debug
    com.alibaba.druid.pool: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    #url: ENC(N55qN9yxOuboFtK0H+ivxApdKZrzAcVxwkFYMN7p+4rTHwRAsWd6fOETmh4SW55MWgQJh91RBhUG5TSy557lQo+/wjcb/LK3Hu0x6E2ZIUTC6GJAVuaaGDJdEV2iC1TC)
    #username: ENC(BZLHGb4UjsoE+sr6mgwCl/PhQQnOBHzL)
    #password: ENC(ZWfu/1qlvAuRo0wo1CKBTBfrd8lp38k1epajUh+qEYWwOlqv5+PKexqT9i36XCL6CzcCbQBlS3+LvMjRqY5DiQ==)
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    host: 124.193.171.213
    port: 36379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000s
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
server:
  port: 8102